# Generated by Django 3.1 on 2021-02-02 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafica', '0029_auto_20210125_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Data di stipula')),
                ('school_year', models.CharField(help_text='aaaa/aaaa', max_length=9, verbose_name='Anno scolastico')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Data di avvio')),
                ('end_date', models.DateField(auto_now=True, verbose_name='Data di conclusione')),
                ('wage', models.FloatField(verbose_name='Compenso')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_staff', to='anagrafica.staff', verbose_name='Collaboratore')),
                ('training_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_unit', to='anagrafica.trainingunit', verbose_name='Unità formativa')),
            ],
        ),
    ]
