# Generated by Django 3.1 on 2021-02-02 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacheragreement',
            options={'verbose_name': 'Contratto docente', 'verbose_name_plural': 'Contratti docente'},
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data di stipula'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data di conclusione'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data di avvio'),
        ),
    ]
