# Generated by Django 3.1 on 2021-02-02 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0002_auto_20210202_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheragreement',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 19, 5, 2, 233394), verbose_name='Data di stipula'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 19, 5, 2, 233524), verbose_name='Data di conclusione'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 19, 5, 2, 233510), verbose_name='Data di avvio'),
        ),
    ]
