# Generated by Django 3.1 on 2021-02-02 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0003_auto_20210202_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheragreement',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 18, 6, 12, 151892, tzinfo=utc), verbose_name='Data di stipula'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 18, 6, 12, 152048, tzinfo=utc), verbose_name='Data di conclusione'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 2, 18, 6, 12, 152031, tzinfo=utc), verbose_name='Data di avvio'),
        ),
    ]
