# Generated by Django 3.1 on 2021-02-02 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0005_auto_20210202_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheragreement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di stipula'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data di avvio'),
        ),
    ]
