# Generated by Django 3.1 on 2021-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0006_auto_20210202_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheragreement',
            name='contract_type',
            field=models.CharField(choices=[('C', 'Collaborazione/P.IVA'), ('P', 'Contratto a progetto'), ('D', 'Tempo determinato'), ('I', 'Tempo indeterminato')], default='P', max_length=50, verbose_name='Tipo di contratto'),
        ),
    ]
