# Generated by Django 3.1 on 2021-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0007_teacheragreement_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('barcode', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Codice')),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('brand', models.CharField(max_length=128, null=True, verbose_name='Marca')),
                ('description', models.TextField(null=True, verbose_name='Descrizione')),
                ('department', models.CharField(choices=[('E', 'Elettricità'), ('U', 'Utensileria'), ('I', 'Idraulica'), ('F', 'Ferramenta')], max_length=50, null=True, verbose_name='Reparto')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Quantità in magazzino')),
                ('price', models.FloatField(null=True, verbose_name='Costo unitario')),
            ],
            options={
                'verbose_name': 'Materiale',
                'verbose_name_plural': 'Materiali',
            },
        ),
    ]
