# Generated by Django 3.1 on 2021-05-23 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0008_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('+', 'Entrata'), ('-', 'Uscita')], max_length=9, verbose_name='Tipo di movimento')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Quantità')),
                ('movement_date', models.DateField(default=datetime.datetime.now, verbose_name='Data')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='amministrazione.warehouse', verbose_name='Prodotto')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimenti',
            },
        ),
    ]
