# Generated by Django 3.1 on 2021-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0009_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
    ]
