# Generated by Django 3.1 on 2021-05-24 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0012_auto_20210524_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='last_movement',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data ultimo movimento'),
        ),
    ]
