# Generated by Django 3.1 on 2021-05-28 13:40

import amministrazione.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Ordine chiuso'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[amministrazione.models.check_if_closed], verbose_name='Numero di ordine'),
        ),
    ]
