# Generated by Django 3.1 on 2021-08-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0054_auto_20210831_1235'),
        ('amministrazione', '0015_auto_20210528_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheragreement',
            name='training_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_related_unit', to='anagrafica.trainingunit', verbose_name='Unità formativa'),
        ),
    ]
