# Generated by Django 3.1 on 2021-09-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0016_auto_20210831_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheragreement',
            name='date',
            field=models.DateField(verbose_name='Data di stipula'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='end_date',
            field=models.DateField(verbose_name='Data di conclusione'),
        ),
        migrations.AlterField(
            model_name='teacheragreement',
            name='start_date',
            field=models.DateField(verbose_name='Data di avvio'),
        ),
    ]
