# Generated by Django 3.1 on 2021-10-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0057_student_is_withdrawn'),
        ('amministrazione', '0017_auto_20210902_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now=True, verbose_name='Orario')),
                ('in_out', models.CharField(choices=[('E', 'Entrata'), ('U', 'Uscita')], default='E', max_length=7, verbose_name='Entrata/Uscita')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_for_employee', to='anagrafica.staff', verbose_name='Impiegato')),
            ],
            options={
                'verbose_name': 'Entrata time card',
                'verbose_name_plural': 'Entrate time card',
            },
        ),
    ]
