# Generated by Django 3.1 on 2021-11-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0019_auto_20211007_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecardentry',
            name='entry_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
