# Generated by Django 3.1 on 2021-11-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0020_auto_20211112_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecardentry',
            name='entry_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Ora'),
        ),
    ]
