# Generated by Django 3.1 on 2022-01-30 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amministrazione', '0021_auto_20211112_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='last_movement',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data ultimo movimento'),
        ),
    ]
