# Generated by Django 3.0.8 on 2020-08-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0002_auto_20200804_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tutor'),
        ),
        migrations.AddField(
            model_name='disciplinarymeasure',
            name='teacher_reporting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reporting', to='anagrafica.Staff', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='disciplinarymeasure',
            name='tutor_reporting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reporting', to='anagrafica.Staff', verbose_name='Tutor'),
        ),
        migrations.AddField(
            model_name='staff',
            name='vat',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True, verbose_name='P. IVA'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='anagrafica.Sector', verbose_name='Materie'),
        ),
    ]
