# Generated by Django 3.0.8 on 2020-08-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0007_auto_20200807_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.ManyToManyField(blank=True, default='', to='anagrafica.Sector', verbose_name='Materie'),
        ),
    ]
