# Generated by Django 3.1 on 2020-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0011_auto_20201023_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='C.F.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='handicap',
            field=models.BooleanField(blank=True, null=True, verbose_name='Portatore di handicap'),
        ),
        migrations.AlterField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Luogo di nascita'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CAP'),
        ),
    ]
