# Generated by Django 3.1 on 2020-11-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0012_auto_20201023_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_role_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ruolo del riferimento (1)'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_role_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ruolo del riferimento (2)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email_1',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email di riferimento (1)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email_2',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email di riferimento (2)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_telephone_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono di riferimento (1)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_telephone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono di riferimento (2)'),
        ),
    ]
