# Generated by Django 3.1 on 2020-11-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0013_auto_20201119_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='picture',
            field=models.ImageField(default='default_user.png', upload_to='profile_images', verbose_name='Immagine profilo'),
        ),
    ]
