# Generated by Django 3.1 on 2020-11-24 10:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0018_auto_20201123_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
