# Generated by Django 3.1 on 2020-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0019_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Utente attivo'),
        ),
    ]
