# Generated by Django 3.1 on 2021-01-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0024_auto_20210111_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='chief_legal_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RL - Nome'),
        ),
        migrations.AlterField(
            model_name='company',
            name='chief_legal_place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RL - Nato a'),
        ),
        migrations.AlterField(
            model_name='company',
            name='chief_legal_resident_in',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RL - Residente in'),
        ),
        migrations.AlterField(
            model_name='company',
            name='chief_legal_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RL - In qualità di'),
        ),
        migrations.AlterField(
            model_name='company',
            name='chief_legal_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsabile legale - Cognome'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referente aziendale'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Ragione sociale'),
        ),
        migrations.AlterField(
            model_name='company',
            name='operational_headquarters_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede operativa - Indirizzo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='operational_headquarters_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede operativa - Comune'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_office_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede legale - Indirizzo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_office_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede legale - Comune'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
    ]
