# Generated by Django 3.1 on 2021-01-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0025_auto_20210111_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinarymeasure',
            name='teacher_reporting',
            field=models.ForeignKey(blank=True, default='Docente non in elenco', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reporting', to='anagrafica.staff', verbose_name='Docente'),
        ),
    ]
