# Generated by Django 3.1 on 2021-01-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0026_auto_20210112_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinarymeasure',
            name='note_type',
            field=models.CharField(choices=[('COLLOQUIO', 'Colloquio con tutor'), ('DIREZIONE', 'Colloquio con preside'), ('FAMIGLIA', 'Incontro con famiglia'), ('SOSPENSIONE', 'Espulsione')], max_length=20, verbose_name='Proposta'),
        ),
    ]
