# Generated by Django 3.1 on 2021-01-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0027_auto_20210114_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='specialization',
        ),
    ]
