# Generated by Django 3.1 on 2021-01-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0028_remove_staff_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinarymeasure',
            name='note_type',
            field=models.CharField(choices=[('COLLOQUIO', 'Colloquio con tutor'), ('DIREZIONE', 'Colloquio con preside'), ('FAMIGLIA', 'Incontro con famiglia'), ('SOSPENSIONE', 'Sospensione')], max_length=20, verbose_name='Proposta'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contract_hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ore da contratto (settimanali)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='early_exit',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Uscita anticipata'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postponed_entry',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Entrata posticipata'),
        ),
    ]
