# Generated by Django 3.1 on 2021-02-03 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0029_auto_20210125_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingunit',
            name='teacher',
        ),
    ]
