# Generated by Django 3.1 on 2021-02-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0030_remove_trainingunit_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data di inizio')),
                ('end_date', models.DateField(verbose_name='Data di fine')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_in_stage', to='anagrafica.course', verbose_name='Corso')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stage',
            },
        ),
    ]
