# Generated by Django 3.1 on 2021-02-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0032_stage_re_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'task': 'T'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stage_tutor', to='anagrafica.staff', verbose_name='Tutor'),
        ),
    ]
