# Generated by Django 3.1 on 2021-02-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0033_stage_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='medical_examination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data visita medica'),
        ),
    ]
