# Generated by Django 3.1 on 2021-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0034_stage_medical_examination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='medical_examination_renoval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data rinnovo visita medica'),
        ),
        migrations.AddField(
            model_name='stage',
            name='safety_certificate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data attestato sicurezza'),
        ),
    ]
