# Generated by Django 3.1 on 2021-02-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0036_sector_stage_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingunit',
            name='kind',
            field=models.CharField(choices=[('L', 'Laboratorio'), ('U', 'Teoria, materie umanistiche'), ('T', 'Teoria, materie pratiche')], default='U', max_length=1, verbose_name='Tipo di materia'),
        ),
    ]
