# Generated by Django 3.1 on 2021-02-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0037_trainingunit_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='contract_expiration',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='contract_hours',
        ),
    ]
