# Generated by Django 3.1 on 2021-02-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0038_auto_20210210_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='contract_type',
        ),
    ]
