# Generated by Django 3.1 on 2021-05-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0039_remove_staff_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='holidays',
            field=models.CharField(blank=True, max_length=256, verbose_name='Periodo di vacanze'),
        ),
    ]
