# Generated by Django 3.1 on 2021-07-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0041_course_official_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinarymeasure',
            name='read_by_parents',
            field=models.BooleanField(default=False, verbose_name='Documento letto dai genitori'),
        ),
    ]
