# Generated by Django 3.1 on 2021-07-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0042_disciplinarymeasure_read_by_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinarymeasure',
            name='read_by_parents',
        ),
        migrations.AddField(
            model_name='disciplinarymeasure',
            name='read_by_parents_of',
            field=models.TextField(blank=True, null=True, verbose_name='Documento letto dai genitori'),
        ),
    ]
