# Generated by Django 3.1 on 2021-07-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0043_auto_20210714_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinarymeasure',
            name='read_by_parents_of',
            field=models.TextField(blank=True, null=True, verbose_name='Documento letto dai genitori di'),
        ),
    ]
