# Generated by Django 3.1 on 2021-07-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0046_remove_disciplinarymeasure_read_by_parents_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinarymeasureread',
            name='measure',
            field=models.CharField(max_length=10, verbose_name='Segnalazione'),
        ),
        migrations.AlterField(
            model_name='disciplinarymeasureread',
            name='student',
            field=models.CharField(max_length=16, verbose_name='Studente'),
        ),
    ]
