# Generated by Django 3.1 on 2021-07-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0047_auto_20210715_1107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disciplinarymeasureread',
            unique_together={('measure', 'student')},
        ),
    ]
