# Generated by Django 3.1 on 2021-07-16 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0048_auto_20210715_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinarymeasureread',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data di creazione'),
        ),
    ]
