# Generated by Django 3.1 on 2021-07-19 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0049_disciplinarymeasureread_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=127, verbose_name='Oggetto')),
                ('content', models.TextField(verbose_name='Contenuto')),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='Data di creazione')),
                ('read_by_family', models.BooleanField(default=False, verbose_name='Letta dalla famiglia')),
                ('date_of_reading', models.DateField(blank=True, null=True, verbose_name='Letta in data')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicazione_per', to='anagrafica.student', verbose_name='Allievo')),
            ],
            options={
                'verbose_name': 'Comunicazione alla famiglia',
                'verbose_name_plural': 'Comunicazioni alle famiglie',
                'ordering': ['-created_at'],
            },
        ),
    ]
