# Generated by Django 3.1 on 2021-07-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0050_communications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communications',
            new_name='Communication',
        ),
    ]
