# Generated by Django 3.1 on 2021-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0051_auto_20210719_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='building',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='floor',
        ),
        migrations.AddField(
            model_name='classroom',
            name='schedule_name',
            field=models.CharField(help_text='Es. LAB-ELE1', max_length=15, null=True, verbose_name='Nome per orario'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name="Nome dell'aula"),
        ),
    ]
