# Generated by Django 3.1 on 2021-08-31 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0053_auto_20210727_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinarymeasure',
            options={'ordering': ['-reporting_date'], 'verbose_name': 'Provvedimento disciplinare', 'verbose_name_plural': 'Provvedimenti disciplinari'},
        ),
    ]
