# Generated by Django 3.1 on 2021-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0054_auto_20210831_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Ditta', 'verbose_name_plural': 'Ditte'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='chief_legal_birth',
        ),
        migrations.RemoveField(
            model_name='company',
            name='chief_legal_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='chief_legal_place_of_birth',
        ),
        migrations.RemoveField(
            model_name='company',
            name='chief_legal_resident_in',
        ),
        migrations.RemoveField(
            model_name='company',
            name='chief_legal_role',
        ),
        migrations.RemoveField(
            model_name='company',
            name='commerce_registration',
        ),
        migrations.RemoveField(
            model_name='company',
            name='registered_office_address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='registered_office_city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vat',
        ),
        migrations.AlterField(
            model_name='company',
            name='chief_legal_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsabile legale'),
        ),
    ]
