# Generated by Django 3.1 on 2021-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0055_auto_20210902_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Corso concluso'),
        ),
    ]
