# Generated by Django 3.1 on 2021-09-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0056_course_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_withdrawn',
            field=models.BooleanField(default=False, verbose_name='Ritirato'),
        ),
    ]
