# Generated by Django 3.1 on 2021-11-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0058_staff_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='badge',
            field=models.SlugField(blank=True, max_length=25, null=True, unique=True, verbose_name='Codice badge'),
        ),
    ]
