# Generated by Django 3.1 on 2020-11-04 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0002_teacherattendance_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='hours_attended',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='training_unit',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='hours_lost',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)], verbose_name='Ore perse'),
        ),
    ]
