# Generated by Django 3.1 on 2020-11-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0003_auto_20201104_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='event',
            field=models.CharField(choices=[('P', 'Presente'), ('R', 'Ritardo'), ('U', 'Uscita anticipata')], default='P', max_length=50, verbose_name='Evento'),
        ),
    ]
