# Generated by Django 3.1 on 2020-11-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0004_studentattendance_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='event',
            field=models.CharField(choices=[('P', 'Presente'), ('R', 'Ritardo'), ('U', 'Uscita anticipata'), ('A', 'Assente')], default='P', max_length=50, verbose_name='Evento'),
        ),
    ]
