# Generated by Django 3.1 on 2020-11-26 12:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafica', '0020_staff_active'),
        ('frequenze', '0005_auto_20201116_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=128, verbose_name='Testo')),
                ('solved', models.BooleanField(default=False, verbose_name='Risolto')),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='Data di creazione')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator_user', to=settings.AUTH_USER_MODEL, verbose_name='Creata da')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_with_note', to='anagrafica.student', verbose_name='Studente')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Note',
            },
        ),
    ]
