# Generated by Django 3.1 on 2021-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0008_auto_20201223_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='event',
            field=models.CharField(choices=[('P', 'Presente'), ('R', 'Ritardo'), ('U', 'Uscita anticipata'), ('A', 'Assente'), ('R/U', 'Ritardo e uscita ant.'), ('F', 'Ore perse in FAD')], default='P', max_length=50, verbose_name='Evento'),
        ),
    ]
