# Generated by Django 3.1 on 2021-01-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0023_auto_20210108_1138'),
        ('frequenze', '0010_note_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCommunication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Anno')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mese')),
                ('text', models.TextField(blank=True, verbose_name='Comunicazioni')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_reference_course', to='anagrafica.course', verbose_name='Corso')),
            ],
        ),
    ]
