# Generated by Django 3.1 on 2021-01-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0011_familycommunication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familycommunication',
            options={'verbose_name': 'Comunicazione', 'verbose_name_plural': 'Comunicazioni'},
        ),
    ]
