# Generated by Django 3.1 on 2021-01-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0027_auto_20210114_1100'),
        ('frequenze', '0012_auto_20210112_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_with_note', to='anagrafica.student', verbose_name='Studente'),
        ),
    ]
