# Generated by Django 3.1 on 2021-02-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0013_auto_20210114_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='event',
            field=models.CharField(choices=[('P', 'Presente'), ('R', 'Ritardo'), ('U', 'Uscita anticipata'), ('A', 'Assente'), ('R/U', 'Ritardo e uscita ant.'), ('S', 'Sospensione'), ('F', 'Ore perse in FAD')], default='P', max_length=50, verbose_name='Evento'),
        ),
    ]
