# Generated by Django 3.1 on 2021-02-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0036_sector_stage_objectives'),
        ('frequenze', '0014_auto_20210205_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lun', 'Lunedì'), ('Mar', 'Martedì'), ('Mer', 'Mercoledì'), ('Gio', 'Giovedì'), ('Ven', 'Venerdì')], max_length=12, verbose_name='Giorno')),
                ('hour', models.CharField(choices=[(1, '08.00-9.00'), (2, '09.00-10.00'), (3, '10.00-11.00'), (4, '11.00-12.00'), (5, '12.00-13.00'), (6, '13.00-14.00'), (7, '14.00-15.00'), (8, '15.00-16.00'), (9, '16.00-17.00')], max_length=12, verbose_name='Ora')),
                ('training_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_related_lesson', to='anagrafica.trainingunit', verbose_name='Unità Formativa')),
            ],
            options={
                'verbose_name': 'Lezione',
                'verbose_name_plural': 'Lezioni',
            },
        ),
    ]
