# Generated by Django 3.1 on 2021-05-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0019_auto_20210215_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.BooleanField(default=False, verbose_name='Promemoria'),
        ),
    ]
