# Generated by Django 3.1 on 2021-07-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0051_auto_20210719_1137'),
        ('frequenze', '0021_note_reminder_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=12, verbose_name='Giorno')),
                ('hour', models.CharField(max_length=12, verbose_name='Ora')),
                ('training_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uf_send_related_lesson', to='anagrafica.trainingunit', verbose_name='Unità Formativa')),
            ],
            options={
                'verbose_name': 'Lezione inviata',
                'verbose_name_plural': 'Lezioni inviate',
            },
        ),
    ]
