# Generated by Django 3.1 on 2021-07-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0053_auto_20210727_1239'),
        ('frequenze', '0023_auto_20210726_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_for_lesson', to='anagrafica.classroom', verbose_name='Aula'),
        ),
    ]
