# Generated by Django 3.1 on 2021-08-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0024_lesson_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('Lun', '1 - Lunedì'), ('Mar', '2 - Martedì'), ('Mer', '3 - Mercoledì'), ('Gio', '4 - Giovedì'), ('Ven', '5 - Venerdì')], max_length=12, verbose_name='Giorno'),
        ),
    ]
