# Generated by Django 3.1 on 2021-08-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0025_auto_20210831_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='day',
            field=models.CharField(choices=[('Lun', 'Lunedì'), ('Mar', 'Martedì'), ('Mer', 'Mercoledì'), ('Gio', 'Giovedì'), ('Ven', 'Venerdì')], max_length=12, verbose_name='Giorno'),
        ),
    ]
