# Generated by Django 3.1 on 2021-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0027_auto_20211206_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='event',
            field=models.CharField(choices=[('P', 'Presente'), ('R', 'Ritardo'), ('G', 'Ritardo giustificato'), ('U', 'Uscita anticipata'), ('A', 'Assente'), ('RU', 'Ritardo e uscita ant.'), ('S', 'Sospensione'), ('F', 'Ore perse in FAD')], default='P', max_length=50, verbose_name='Evento'),
        ),
    ]
