# Generated by Django 3.1 on 2021-12-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frequenze', '0031_lessondone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessondone',
            name='related_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_lesson_in_schedule', to='frequenze.lessonwithdate', verbose_name='Lezione relativa in orario'),
        ),
    ]
